theme = "base16"

[editor]
line-number = "relative"
[editor.lsp]
display-messages = true

[keys.normal]
" " = "file_picker"
" w" = ":w"
" q" = ":q"
"esc" = ["collapse_selection", "keep_primary_selection"]
